project_id = "egcahlohmpfkgdouxcdj"

[functions.delete-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.assign-faculty-role]
verify_jwt = false

[functions.send-result-email]
verify_jwt = false
